C = g++
aes: src/aes.cpp
	$(C) src/aes.cpp -o build/aes -s -l:libcryptopp.a

tripleDes: src/tripleDes.cpp
	$(C) src/tripleDes.cpp -o build/tripleDes -s -l:libcryptopp.a

idea: src/idea.cpp
	$(C) src/idea.cpp -o build/idea -s -l:libcryptopp.a