C = g++
pseudorandom_autoseeded: src/pseudorandom_autoseeded.cpp
	$(C) src/pseudorandom_autoseeded.cpp -o build/pseudorandom_autoseeded -s -l:libcryptopp.a

ofb_random: src/ofb_random.cpp
	$(C) src/ofb_random.cpp -o build/ofb_random -s -l:libcryptopp.a