C = g++
ecb: src/ecb.cpp
	$(C) src/ecb.cpp -o build/ecb -s -l:libcryptopp.a

cbc: src/cbc.cpp
	$(C) src/cbc.cpp -o build/cbc -s -l:libcryptopp.a

ctr: src/ctr.cpp
	$(C) src/ctr.cpp -o build/ctr -s -l:libcryptopp.a

ofb: src/ofb.cpp
	$(C) src/ofb.cpp -o build/ofb -s -l:libcryptopp.a

cfb: src/cfb.cpp
	$(C) src/cfb.cpp -o build/cfb -s -l:libcryptopp.a